name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install Dependencies
        run: npm install  

      - name: Run Tests
        run: npm test  

      - name: Build Application
        run: npm run build  
      - name: Deploy Application
        run: |
          pm2 stop all || true  # Stop any existing instance of the app (using pm2)
          pm2 start npm --name "my-app" -- start  # Start the app using pm2
